version: 2
executors:
  backend-executor:
    working_directory: ~/lab-eshop/backend
    docker:
      image: circleci/ruby:2.4.2-jessie-node
jobs:
  build:
    executor: backend-executor
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout:
          path: ~/lab-eshop
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - backend-bundle-{{ checksum "Gemfile.lock" }}
            - backend-bundle-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rails-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - backend-yarn-{{ checksum "yarn.lock" }}
            - backend-yarn-
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: backend-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
